<?php
/** @var \BobGroup\BobGo\Block\TrackingBlock $block */
$shipmentData = $block->getTrackingData();
?>

<style>
    .track-order-container {
        max-width: 600px;
        margin: auto;
        padding: 20px;
        border: 1px solid #ddd;
        background-color: #f9f9f9;
    }

    .tracking-details h2 {
        margin-top: 20px;
    }

    .tracking-details p {
        margin: 5px 0;
    }

    footer {
        margin-top: 20px;
        font-size: 0.9em;
        text-align: center;
    }

    footer img {
        display: block;
        margin: 10px auto;
    }
</style>

<div class="track-order-container">
    <?php if (empty($shipmentData)) : ?>
        <form action="<?= $block->escapeUrl($block->getUrl('bobgo/tracking/index')) ?>" method="post" class="track-order-form">
            <?= $block->getBlockHtml('formkey') ?>
            <div class="field">
                <label for="order_reference"><?= $block->escapeHtml(__('Order Number/Tracking Reference:')) ?></label>
                <input type="text" id="order_reference" name="order_reference" required>
                <label for="email"><?= $block->escapeHtml(__('Email Address:')) ?></label>
                <input type="email" id="email" name="email" required>
            </div>
            <br>
            <div class="actions-toolbar">
                <button type="submit" class="action submit primary"><?= $block->escapeHtml(__('Track Order')) ?></button>
            </div>
        </form>
    <?php endif; ?>

    <?php if ($shipmentData && is_array($shipmentData)) : ?>
        <div class="tracking-details">
            <h2><?= $block->escapeHtml(__('Shipping Details')) ?></h2>

            <?php if (isset($shipmentData['shipment_tracking_reference'])) : ?>
                <p><strong><?= $block->escapeHtml(__('Shipment:')) ?></strong> <?= $block->escapeHtml($shipmentData['shipment_tracking_reference']) ?></p>
            <?php endif; ?>

            <?php if (isset($shipmentData['order_number'])) : ?>
                <p><strong><?= $block->escapeHtml(__('Order:')) ?></strong> <?= $block->escapeHtml(ltrim($shipmentData['order_number'], '0')) ?></p>
            <?php endif; ?>

            <?php if (isset($shipmentData['courier_name'])) : ?>
                <p><strong><?= $block->escapeHtml(__('Courier:')) ?></strong> <?= $block->escapeHtml($shipmentData['courier_name']) ?></p>
            <?php endif; ?>

            <br>
            <h2><?= $block->escapeHtml(__('Tracking Details')) ?></h2>

            <?php if (isset($shipmentData['status']) && isset($shipmentData['status_friendly'])) : ?>
                <?php if ($shipmentData['status'] === 'pending-collection') : ?>
                    <p><?= $block->escapeHtml(__('Your shipment will be collected soon. Please check back later for more information.')) ?></p>
                    <p><strong><?= $block->escapeHtml(__('Current Status:')) ?></strong> <?= $block->escapeHtml($shipmentData['status_friendly']) ?></p>
                <?php elseif (in_array($shipmentData['status'], ['cancelled-by-courier', 'cancelled'])) : ?>
                    <p><?= $block->escapeHtml(__('The shipment has been cancelled.')) ?></p>
                    <p><strong><?= $block->escapeHtml(__('Current Status:')) ?></strong> <?= $block->escapeHtml($shipmentData['status_friendly']) ?></p>
                <?php else : ?>
                    <?php if (empty($shipmentData['checkpoints'])) : ?>
                        <p><?= $block->escapeHtml(__('Tracking information is not yet available. Please check back later for more information.')) ?></p>
                    <?php else : ?>
                        <p><?= $block->escapeHtml(__('Tracking information is available below:')) ?></p>
                        <table id="table_checkpoints">
                            <thead>
                            <tr>
                                <th><?= $block->escapeHtml(__('Date and Time')) ?></th>
                                <th><?= $block->escapeHtml(__('Status')) ?></th>
                                <th><?= $block->escapeHtml(__('Message')) ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($shipmentData['checkpoints'] as $checkpoint) : ?>
                                <tr>
                                    <td>
                                        <?php
                                        try {
                                            $timeDate = new DateTime($checkpoint['time']);
                                            echo $block->escapeHtml($timeDate->format('Y M d, H:i'));
                                        } catch (\Exception $e) {
                                            echo $block->escapeHtml($checkpoint['time'] ?? '');
                                        }
                                        ?>
                                    </td>
                                    <td><strong><?= $block->escapeHtml($checkpoint['status_friendly'] ?? '') ?></strong></td>
                                    <td><?= $block->escapeHtml($checkpoint['message'] ?? '') ?></td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        </div>

    <br>
        <footer>
            <p>
                <?= $block->escapeHtml(
                    sprintf(
                        __('For additional information, please contact %s (%s) and quote tracking reference %s.'),
                        $shipmentData['courier_name'] ?? '',
                        $shipmentData['courier_phone'] ?? '',
                        $shipmentData['id'] ?? ''
                    )
                ) ?>
            </p>
            <img id="show_branding" class="image"
                 src="https://ik.imagekit.io/z1viz85yxs/prod-v3/bobgo/corporate-identity/bobgo_logo_smart_shipping.png?tr=w-400"
                 alt="Bob Go logo"  style="width: 200px;">
        </footer>
    <?php else : ?>
    <br>
        <p><?= $block->escapeHtml(__('No tracking data available.')) ?></p>
    <?php endif; ?>
</div>
